### ISSUE TITLE
Cards Not Showing Up

### ISSUE THREAD

**Issue by Malith97** [SimCoderYoutube/TinderClone#10]
my code is exactly same as yours and everything works fine but **swipe cards are not showing**. and there are no any solutions in your forum . found any solution??

**Comment by nirmita123** [comment]
I'm facing the same issue. Could you please tell how you solved it?

**Comment by Malith97** [comment]
It's better you understand the code first in his tutorial and go to the
github and download his repository and change the package name and make a
new database and configure it and make the changes that you want. that's
how i solve my issue
